version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 3001:5432
    environment:
      - DB_USER=postgres
      - POSTGRES_PASSWORD=development
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
